version: "3"

services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    env_file: ./packages/frontend/.env
    depends_on:
      - reverse-proxy
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.docker.localhost`)"
